# Generated by Django 4.0.8 on 2024-09-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Category',
            new_name='category',
        ),
    ]
